sonar.projectKey=software-validation-testing-project
sonar.projectName=Software Validation Testing Project
sonar.projectVersion=1.0
sonar.sources=Backend,Frontend
sonar.tests=Backend.Tests,Backend.Tests.UI
sonar.exclusions=**/node_modules/**,**/obj/**,**/bin/**,**/*.designer.cs
sonar.test.inclusions=Backend.Tests/**,Backend.Tests.UI/**
sonar.cs.opencover.reportsPaths=**/TestResults/**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/TestResults/*.trx
sonar.javascript.lcov.reportPaths=Frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
